version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - /data/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis
    restart: always

  collabora:
    image: collabora/code:latest
    restart: always
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    volumes:
      - /etc/nixos/docker/nextcloud/loolwsd.xml:/etc/loolwsd/loolwsd.xml

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
      - redis
    volumes:
      - /srv/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/html:/var/www/html
    environment:
      - OVERWRITEHOST=${NEXTCLOUD_HOST}
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}

  cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - /srv/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    links:
      - db
      - redis

  web:
    image: nginx
    restart: always
    ports:
      - 8081:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
